# Generated by Django 6.0 on 2026-01-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=50)),
                ('horizon_months', models.IntegerField(default=6)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('test_size', models.IntegerField(default=6)),
                ('n_lags', models.IntegerField(default=3)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='core.upload')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_month', models.DateField()),
                ('y_pred', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.forecastrun')),
            ],
            options={
                'ordering': ['forecast_month'],
                'unique_together': {('run', 'forecast_month')},
            },
        ),
    ]
