# Generated by Django 6.0 on 2026-01-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forecastrun_forecastresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('y_true', models.FloatField()),
                ('y_pred', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.forecastrun')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('run', 'month')},
            },
        ),
    ]
