# Generated by Django 6.0 on 2026-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='cv_mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='cv_mape',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='cv_rmse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
